### ISSUE TITLE
Beispiel Audiofile?

### ISSUE THREAD

**Issue by stefangrotz** [thorstenMueller/deep-learning-german-tts#1]
Hallo,
zunächste einmal vielen Dank für deine Arbeit, das ist ein großartiges Projekt und ich bin gespannt was sich daraus alles entwickelt. Es wäre aber schön wenn Du ein Beispiel-Audiofile bereitstellen würdest, damit man sich ein Bild vom Datensatz machen kann ohne alle Dateien herunter laden zu müssen. So weiß man schnell, ob die Stimme passend für das eigene Projekt ist.

Beste Grüße und Danke,
Stefan

**Comment by thorstenMueller** [comment]
Vielen Dank für das Kompliment.
Ich habe einige Samples meiner Originalstimme bereitgestellt.

**Comment by stefangrotz** [comment]
Super, danke :)
