### ISSUE TITLE
Help when training for new Language

### ISSUE THREAD

**Issue by xoxoxo13102020** [thorstenMueller/deep-learning-german-tts#11]
Could you please give me information about training mozillatts with my own dataset? Do I need only voices and its text ? 

I prepare a dataset from audio books.Like LJSpeech I have .wav 16 bit PCM Mono sounds. Do I need anything else could you tell me the steps that I should look at.

**Comment by thorstenMueller** [comment]
Hello @xoxoxo13102020.
If you wanna build your own tts model i’d recommend reading and following these instructions (https://github.com/mozilla/tts).
You need a huge amount of clean and trimmed audio data and a csv file with the recorded text. 

If you take your voice data from audio books try to find recordings with a constant recording pace and voice.
In case you want to record your own dataset see some tipps here: https://github.com/mozilla/TTS/wiki/Dataset#what-makes-a-good-dataset.

If i get it right you’ve already joined our TTS community on Mozilla discourse. If not, feel free to do so (https://discourse.mozilla.org/c/tts/285).

Best of luck.

**Comment by xoxoxo13102020** [comment]
The question "How can I train my own model" includes an answer  as a step like this """ **If you have a dataset with a different alphabet than English Latin, you need to add your alphabet in utils.text.symbols.
If you use phonemes for training and your language is supported here, you don't need to do that**  """ Do you know how to use phonemes for training how could I set this as phonemes or as letter? I want to use Turkish alphabet which phonemes supported by espeak.

**Comment by thorstenMueller** [comment]
I've seen you asked the question in Mozilla TTS discourse too and already got helpful feedback.
https://github.com/mozilla/TTS/issues/564

**Comment by xoxoxo13102020** [comment]
unfortunately I couldnt find an exact answer to my questions. :( 
For some reason, the answers are always indirect.

**Comment by thorstenMueller** [comment]
Okay @xoxoxo13102020 .
I'd say let's move general discussion to your Mozilla thread cause that's the place where all the TTS professionals are. There should all your questions get helpfully answered.

I'm closing this issue now.
