### ISSUE TITLE
Question: Use voice for voice adjustment. 

### ISSUE THREAD

**Issue by ChrisChross** [thorstenMueller/deep-learning-german-tts#19]
Hei @thorstenMueller,

thanks for sharing this dataset with the world. 
I check out the Colab notebook and I am impressed by the results.
As I want to have a TTS for my own voice, I wanted to know if I could 
somehow adjust your voice, retrain the model and get similar results? 

Best regards 
Chris

**Comment by thorstenMueller** [comment]
Hello @ChrisChross .

I know that there are some efforts to transfer an existing model to another speaker but i'm unsure how good this works right now.
Maybe you could use my tacotron2 model and train a vocoder with recordings from you, but this will still have my voice flow and speed of talk. 

I'd recommend to ask in coqui discussions (https://github.com/coqui-ai/TTS/discussions) as there are helpful people having much more experience in multispeaker or transfering a model to another voice than i have.

**Comment by thorstenMueller** [comment]
I'll close this issue, but feel free to start a discussion on coqui if topic is still active.
