### ISSUE TITLE
Text file 

### ISSUE THREAD

**Issue by guanjianyu** [thorstenMueller/deep-learning-german-tts#2]
Hi, really thanks for your effort to make a dataset. But where can I find corresponding text file

**Comment by thorstenMueller** [comment]
When dataset is ready to be published (i'm still recording currently) it will be in LJSpeech format. Basically it has a metadata.csv (text and string length) file besides the wav files.

**Comment by thorstenMueller** [comment]
Download links are currently unavailable since new model training (tacotron v1 and v2) is in progress. I'll publish new download urls when the new models are available.
