### ISSUE TITLE
Do you have high quality audio?

### ISSUE THREAD

**Issue by ZDisket** [thorstenMueller/deep-learning-german-tts#20]
Since all the downloads are 22.05KHz, I was wondering if you had the original (usually 48, 96 or 44.1KHz) high sampling rate recordings.
From my experience it is trivial to train models that output high-fidelity audio.

**Comment by thorstenMueller** [comment]
Original recordings have a samplerate of 44k. But these are not optimized and because many recordings where made with a cheap usb microphone they're not useable without a big effort on optimization. For now i've not planned to optimize and/or release original recordings.

**Comment by ZDisket** [comment]
What do you mean by optimization? I can do audio processing.

**Comment by thorstenMueller** [comment]
You won't get good results when using original 44k sample rate files. So i recommend using the released 22k version.

**Comment by thorstenMueller** [comment]
Guude @ZDisket 👋,
i guess this is way obsolete after 4 years, but as it's Thorsten-Voice project 5th birthday 🎉 there's now a FULL 44kHz Thorsten-Voice dataset is now available (incl. neutral, emotional and Hessisch dialect) 😊.
https://huggingface.co/datasets/Thorsten-Voice/TV-44kHz-Full
