### ISSUE TITLE
Cut off sentences (max_decoder_steps) when using "Thorsten-DCA" model with Coqui TTS v0.1.3 

### ISSUE THREAD

**Issue by thorstenMueller** [thorstenMueller/deep-learning-german-tts#22]
When you're using my Thorsten-DCA model with @coqui-ai v0.1.3 you could encounter a problem where longer sentences are cut off and message "max_decoder_steps" is printed (when running TTS on the command line). This is a known issue and will be fixed in next 🐸TTS release (thx 👑 @erogol).

If you can't wait you can apply the fix yourself by adding a line to `config.json`. Location depends on your local operating system. 

Go to:
Linux: ~/.local/share/tts/
Mac: ~/Library/Application Support/tts/
Win: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders (Registry)

And in the subfolder "tts_models--de--thorsten--tacotron2-DCA" find line `"mixed_precision": false,` and add a new line below with following content: `"max_decoder_steps": 2000,`. This should avoid sentences from being cut off.

**Comment by erogol** [comment]
Ohh wait actually it needs no code update. It is only the config file. I can do it now not waiting for the next release :)

**Comment by thorstenMueller** [comment]
Thanks 👑 @erogol for your quick support. It's working (_when you remove previous local downloaded model_ :wink:).
I also wanted to be quick once and made a quick video on how to setup 🐸TTS server in LESS THAN 5 MINUTES.

https://youtu.be/alpI-DnVlO0

**Comment by ronnystandtke** [comment]
Is this *really* fixed? I just run into exactly this issue when trying to TTS a short text with the model thorsten/tacotron2-DDC with a current pip install. Even changing the config file in the model didn't help.
The text I tried to TTS is from the Firefox privacy in German:

> Technische Daten: Um anzuzeigen, welche Geräte mit Ihrem Firefox-Konto synchronisiert sind, und um die Sicherheitsfunktionen zu verbessern, speichern wir das Gerätebetriebssystem, den Browser und die Version, einen Zeitstempel, das Gebietsschema und die gleichen Informationen für andere mit Ihrem Konto verbundenen Geräte. Wenn Sie Ihr Firefox-Konto verwenden, um sich bei anderen Websites oder Diensten anzumelden (wie AMO oder Pocket), erhalten wir von diesen Diensten den Zeitstempel Ihrer derartigen Anmeldungen.

**Comment by thorstenMueller** [comment]
I can reproduce this behavior which might be because one sentence is too long (too many commas in one sentence). I adjusted the phrase a little bit which works for me.

> Technische Daten: Um anzuzeigen, welche Geräte mit Ihrem Firefox-Konto synchronisiert sind, und um die Sicherheitsfunktionen zu verbessern, speichern wir das Gerätebetriebssystem. Den Browser und die Version, einen Zeitstempel. Das Gebietsschema und die gleichen Informationen für andere mit Ihrem Konto verbundenen Geräte. Wenn Sie Ihr Firefox-Konto verwenden, um sich bei anderen Websites oder Diensten anzumelden (wie AMO oder Pocket), erhalten wir von diesen Diensten den Zeitstempel Ihrer derartigen Anmeldungen.

Which just replaces a , with a . in here:
> Zeitstempel. Das Gebietsschema

**Comment by ronnystandtke** [comment]
We have no influence on the texts that are to be spoken with TTS. They are chosen by our students with disadvantage compensation from assignments or their own solutions. So we have to assume that there will always be sentences that are "too long" or contain too many commas.

**Comment by thorstenMueller** [comment]
Hi @ronnystandtke , my Thorsten-Voice is available on Piper TTS too (in low/medium/high quality). Maybe Piper TTS works better for your usecase with longer texts. Might be worth a try.
https://youtu.be/9e1Wt82GKmU?si=yW0ARlBoCSTPpgg7

**Comment by ronnystandtke** [comment]
It absolutely does! I already testet it, was blown away by the streaming audio feature and created a Debian package for the Lernstick Linux distribution including the most important voices: https://packages.lernstick.ch/lernstick/pool/main/l/lernstick-piper/

This will be part of our upcoming Lernstick release based on Debian 12. If you want to give it a shot, the (internal) beta is here: https://customers.lernstick.ch/joerg/
You can run the ISO e.g. in VirtualBox. Copy any text into the clipboard and click on the speaker symbol in the GNOME dock.

We do natural language detection via Apache Tika: https://tika.apache.org/2.8.0/detection.html#Language_Detection
We support German, English, French, Italian and Spanish. If we detect that the clipboard is in German our students hear your great voice. Thank you sooo much! :-)

**Comment by thorstenMueller** [comment]
Wow, thanks for your feedback, @ronnystandtke . I justed played a little bit around with the beta version of "Lernstick" (mostly the TTS part, of course) and it looks and feels amazing 😊.

I'm really happy that my artificial voice is a benefit for your educational use case. May i kindly ask if linking the [Thorsten-Voice project website](https://www.thorsten-voice.de/) is possible on your project website. But this is absolutely optional, of course.

"Lernstick" seems really to be an important and great project 👏.
