### ISSUE TITLE
Retraining deiner Modelle mit eigener Stimme

### ISSUE THREAD

**Issue by padmalcom** [thorstenMueller/deep-learning-german-tts#23]
Hi Thorsten, erstmal danke für den unfassbaren Aufwand, den du hier betreibst!

Ich würde gerne das Thema Retraining angehen, ganz konkret dein Tacotron2 Modell mit meiner Stimme nachtrainieren und schauen, wie die Ergebnisse sind. Ich komme auch aus dem Real Time Voice Cloning von Corentin Jemine, das ja versucht die Embeddings einer eigenen Stimme im Synthesizer zu verwenden, jedoch ist der Erfolg eher mau - die Embeddings haben zu wenig Einfluss, also wäre der nächste Versuch ein Retraining. Deswegen ein Versuch mit coqui.ai.

Meine Frage/Bitte ist nun konkret, ob du die Tacotron2Config zu Verfügung stellen könntest, die du für das Training verwendet hast, ich hab die nirgends in deinen Files gefunden.

Und eher eine Frage aus beiläufigem Interesse: Trainierst du auf einem Nvidia AGX? :)

**Comment by thorstenMueller** [comment]
Hallo @padmalcom .
> Hi Thorsten, erstmal danke für den unfassbaren Aufwand, den du hier betreibst!

Vielen Dank & gerne 😄 .

Du kannst Checkpoint und Konfiguration von meinem Tacotron2 DCA Modell hier runterladen:
https://github.com/coqui-ai/TTS/releases/download/v0.0.11/tts_models--de--thorsten--tacotron2-DCA.zip

Und ja - ich trainiere auf dem AGX 😉 .

**Comment by thorstenMueller** [comment]
Ich schließe den Issue hier.
Bei Bedarf kannst Du ihn gerne wieder öffnen.
