### ISSUE TITLE
"New" model available

### ISSUE THREAD

**Issue by ZDisket** [thorstenMueller/deep-learning-german-tts#24]
> If you trained a model on "Thorsten" dataset please file an issue with some information on it. Sharing a trained model is highly appreciated.

You might find this interesting. I exported the TensorFlowTTS model trained by monatis for use in the TTS program I maintain https://github.com/ZDisket/TensorVox. Now anyone with a Windows 10 machine (and a CPU with AVX support, anything made after 2010 that isn't a Xeon will do) can use your voice in a few clicks. Here's a sample video: https://youtu.be/tY6_xZnkv-A
I'll think of training another one if I have enough GPU credits leftover after my latest project, as this one combined different sources of audio.

**Comment by thorstenMueller** [comment]
Quite impressive - thanks for sharing @ZDisket :clap:

**Comment by ZDisket** [comment]
@thorstenMueller Thank you. Would you be willing to add a short guide (that I can make) to the README so I can close this issue?

**Comment by thorstenMueller** [comment]
I've added a special chapter about your work and linked your github repo so you can add any installations steps there.
https://github.com/thorstenMueller/deep-learning-german-tts#zdisket

If you've any change requests please let me know.

**Comment by thorstenMueller** [comment]
Hi @ZDisket .
Thanks again for your great work 👏 .
I'll close this issue, but feel free to reopen it when you would like to adjust the information on your work in the README.
