### ISSUE TITLE
Model Fine-tuning Problem

### ISSUE THREAD

**Issue by gbvssd** [thorstenMueller/deep-learning-german-tts#25]
Hi Thorsten,
I'm trying to train a TTS model with my own voice in Germany. But if I train a whole new model, the size of the required data set is too large. So I want to fine-tuning your model with my voice.
Regarding this idea, I have some questions 

- how large should my data set be?
- is it possible to use some sentences from your data set to record a small dataset? 
- Is there any requirement for the data set.

And I would like to ask if you have facing out of memory problems when training the TTS model.
Thanks for your help in advance.

**Comment by thorstenMueller** [comment]
Hi @gbvssd .

> how large should my data set be?

There's no fixed value. But as i didn't finetune an existing model myself maybe you can get more help in Coqui TTS discussions (https://github.com/coqui-ai/TTS/discussions), but more data is always better. At least ensure you have a good phoneme coverage.

> is it possible to use some sentences from your data set to record a small dataset?

Feel free to do so.

> Is there any requirement for the data set.

Check my Youtube video at this timestamp to see some tips & tricks.
https://youtu.be/4YT8WZT_x48?t=897

> if you have facing out of memory problems when training the TTS model

When i started my TTS journey with a 4GB GPU "yes" with newer training equipment no ;-).

**Comment by gbvssd** [comment]
Hi Thorsten,
 Thanks for your quick reply, it is very helpful!

**Comment by thorstenMueller** [comment]
Happy that i could help.
I'll close this issue, but feel free to reopen if needed.
