### ISSUE TITLE
Sentences truncated

### ISSUE THREAD

**Issue by hanjo** [thorstenMueller/deep-learning-german-tts#29]
Hi Torsten,

first of all thank you for all your efforts and countless hours you invested into this project. This is simply impressive!

I just started playing around with it yesterday, and after having installed and updated everything (tts should be v0.5.0), I noticed that the resulting wav files seem to be truncated somewhere in the the last word of the sentence.

I tried the following sentences with mixed results:
- Guten Morgen, das Wetter wird heute heiter bis wolkig bei 13 Grad.
- Guten Morgen, das Wetter wird heute heiter bis wolkig bei 13 Grad Celsius.
- Guten Morgen. Wollen wir mal sehen, ob dieser Satz bis zum Ende gesprochen wird.

Attached you can find the sample files.
[samples.zip](https://github.com/thorstenMueller/deep-learning-german-tts/files/7949845/samples.zip)

Any idea what could be causing this?

Thanks
Hanjo

**Comment by thorstenMueller** [comment]
Hi @hanjo ,
thanks for your feedback.

I also recognized this behavior. Some recordings has been cut of too rough, so sometimes last characters are already missing in the original dataset.

This (_and the not optimal speechflow_) are reasons why i'm recording a new dataset. I hope i can release it within the next two month (_without hard cut offs and better speechflow_).

**Comment by hanjo** [comment]
Oh, ok, I see. I just assumed this would be some problem with the synthesizer, not the dataset. Well, looking forward to the new dataset then :-) Thank you once again for your efforts here!

**Comment by thorstenMueller** [comment]
I'm training a model on the new dataset at the moment. It will take some time until release but what i can say for now is, that it will not have problems with cut off phrases.

I'll close this issue but you'll hear once the new dataset and model will be available ;-).
