### ISSUE TITLE
Google Drive download link broken

### ISSUE THREAD

**Issue by Runinho** [thorstenMueller/deep-learning-german-tts#4]
Hi,
thank you for providing such a dataset :)

I have tried to download the dataset but the google drive link (https://drive.google.com/open?id=1NTi-4r3EWl5dw0k2o4Xh92G0OHvhoxAJ) is broken. I only get a 404 not found.

thanks,
Rune

**Comment by thorstenMueller** [comment]
Downloads are currently unavailable since model training for tacotron version 1 and 2 are not finished yet. When final models are available i'll provide new links in README file.
