### ISSUE TITLE
Commercial projects?

### ISSUE THREAD

**Issue by sergium** [thorstenMueller/deep-learning-german-tts#9]
Really great work Thorsten! 

Is it possible to use it in a commercial project?

And are you available (as a consultant) to support us in a new german-tts project?

Please ping me via e-mail.

// Sergey

**Comment by thorstenMueller** [comment]
Thanks @sergium .
I really appreciate your nice feedback.

Feel free to use dataset and/or tts models in commercial projects. If you have a link to your project i'd be happy to get it.

We (a small group of hobby TTS enthusiasts) discuss in mozilla discourse. Please feel free to join our discussion on https://discourse.mozilla.org/t/contributing-my-german-voice-for-tts/
